# ============================================
# Service Account
# ============================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loja-veloz-sa
  namespace: loja-veloz
  labels:
    app.kubernetes.io/name: loja-veloz
    app.kubernetes.io/component: service-account
automountServiceAccountToken: false
